/**
 * dev-proteus configuration
 * Auto-generated by build_hooks.sh
 * Do not edit manually!
 */

#ifndef PROTEUS_CONFIG_H
#define PROTEUS_CONFIG_H

 //=============================================================================
 // Build configuration
 //=============================================================================

 // Emulator connection settings
#define PROTEUS_HOST    "127.0.0.1"
#define PROTEUS_PORT    (4242)

// Which hooks to enable
#define PROTEUS_ENABLE_I2C      (1)
#define PROTEUS_ENABLE_SPI      (0)
#define PROTEUS_ENABLE_UART     (0)
#define PROTEUS_ENABLE_GPIO     (0)

// Debug settings
#define PROTEUS_VERBOSE         (1)
#define PROTEUS_LOG_FILE        "/tmp/dev-proteus.log"


// Release build specific
#define NDEBUG 1  // Disable assert


#endif // PROTEUS_CONFIG_H