# ========== Default configuration ==========
# Emulator connection settings
PROTEUS_HOST="${PROTEUS_HOST:-127.0.0.1}"
PROTEUS_PORT="${PROTEUS_PORT:-4242}"

# Which hooks to enable (1 = enabled, 0 = disabled)
PROTEUS_ENABLE_I2C="${PROTEUS_ENABLE_I2C:-1}"
PROTEUS_ENABLE_SPI="${PROTEUS_ENABLE_SPI:-0}"
PROTEUS_ENABLE_UART="${PROTEUS_ENABLE_UART:-0}"
PROTEUS_ENABLE_GPIO="${PROTEUS_ENABLE_GPIO:-0}"

# Debug settings
PROTEUS_VERBOSE="${PROTEUS_VERBOSE:-1}"
PROTEUS_LOG_FILE="${PROTEUS_LOG_FILE:-/tmp/dev-proteus.log}"

# Cross-compilation prefix (empty by default)
CROSS_COMPILE="${CROSS_COMPILE:-}"

# ========== Generate config.h ==========
PROJECT_ROOT="$(cd "$(dirname "$0")/.." && pwd)"
CONFIG_FILE="$PROJECT_ROOT/hooks/config.h"

echo "Generating $CONFIG_FILE with current settings..."
cat > "$CONFIG_FILE" << EOF
/**
 * dev-proteus configuration
 * Auto-generated by build_hooks.sh
 * Do not edit manually!
 */

#ifndef PROTEUS_CONFIG_H
#define PROTEUS_CONFIG_H

//=============================================================================
// Build configuration
//=============================================================================

// Emulator connection settings
#define PROTEUS_HOST    "$PROTEUS_HOST"
#define PROTEUS_PORT    ($PROTEUS_PORT)

// Which hooks to enable
#define PROTEUS_ENABLE_I2C      ($PROTEUS_ENABLE_I2C)
#define PROTEUS_ENABLE_SPI      ($PROTEUS_ENABLE_SPI)
#define PROTEUS_ENABLE_UART     ($PROTEUS_ENABLE_UART)
#define PROTEUS_ENABLE_GPIO     ($PROTEUS_ENABLE_GPIO)

// Debug settings
#define PROTEUS_VERBOSE         ($PROTEUS_VERBOSE)
#define PROTEUS_LOG_FILE        "$PROTEUS_LOG_FILE"

#endif // PROTEUS_CONFIG_H
EOF

echo "Configuration generated:"
echo "  PROTEUS_HOST=$PROTEUS_HOST"
echo "  PROTEUS_PORT=$PROTEUS_PORT"
echo "  PROTEUS_ENABLE_I2C=$PROTEUS_ENABLE_I2C"
echo "  PROTEUS_ENABLE_SPI=$PROTEUS_ENABLE_SPI"
echo "  PROTEUS_ENABLE_UART=$PROTEUS_ENABLE_UART"
echo "  PROTEUS_ENABLE_GPIO=$PROTEUS_ENABLE_GPIO"
echo "  PROTEUS_VERBOSE=$PROTEUS_VERBOSE"
echo "  PROTEUS_LOG_FILE=$PROTEUS_LOG_FILE"
echo ""

# ========== Build the library ==========
HOOKS_DIR="$PROJECT_ROOT/hooks"
OUTPUT_DIR="$PROJECT_ROOT/output"

cd "$HOOKS_DIR" || exit 1

# Build with cross-compilation if specified
if [ -n "$CROSS_COMPILE" ]; then
    echo "Building with cross-compilation: $CROSS_COMPILE"
    make clean
    make CROSS_COMPILE="$CROSS_COMPILE"
else
    make clean && make
fi

# Check build result
if [ $? -ne 0 ]; then
    echo "❌ Build failed!"
    exit 1
fi

# ========== Copy results ==========
mkdir -p "$OUTPUT_DIR"
cp "$HOOKS_DIR/libproteus_hook.so" "$OUTPUT_DIR/"

echo "✅ Build successful!"
echo "Library copied to: $OUTPUT_DIR/libproteus_hook.so"